#!/usr/bin/env python3
"""Derive the ED status dashboard from directives.jsonl into README.md between markers.

directives.jsonl is the ONLY status authority (USAGE.md); this script renders the derived
view. It refuses (exit 2, no write) on any malformed registry line or missing marker pair.
Output is deterministic: no generation timestamps, rows sorted by directive id.
"""
import argparse
import json
import os
import sys
import tempfile

STATES = {"DESIGN", "VETTED", "GREENLIT", "BUILT-GREEN", "BUILT-RED", "VERIFIED", "REOPENED"}
BEGIN = "<!-- ED-DASHBOARD:BEGIN generated by execution-directives/derive-dashboard.py; do not hand-edit -->"
END = "<!-- ED-DASHBOARD:END -->"


def die(msg):
    print(f"derive-dashboard: {msg}", file=sys.stderr)
    sys.exit(2)


def load(registry):
    if not os.path.isfile(registry):
        die(f"registry not found: {registry}")
    with open(registry, encoding="utf-8") as f:
        lines = f.read().splitlines()
    if not lines:
        die("registry is empty")
    eds = {}
    for n, line in enumerate(lines, 1):
        if not line.strip():
            die(f"line {n}: blank line in append-only registry")
        try:
            d = json.loads(line)
        except json.JSONDecodeError as exc:
            die(f"line {n}: invalid JSON ({exc.msg})")
        missing = {"id", "state", "ts"} - d.keys()
        if missing:
            die(f"line {n}: missing required keys {sorted(missing)}")
        for key in ("id", "ts"):
            if not isinstance(d[key], str):
                die(f"line {n}: {key!r} must be a string, got {type(d[key]).__name__}")
        if d["state"] not in STATES:
            die(f"line {n}: unknown state {d['state']!r} (allowed: {sorted(STATES)})")
        e = eds.setdefault(d["id"], {})
        e["state"], e["ts"] = d["state"], d["ts"]
        if d["state"] == "DESIGN":
            e["tier"] = d.get("tier", "?")
        elif d["state"] == "VETTED":
            f_ = d.get("findings", {})
            e["vet"] = "{}/{}/{}/{} ft{}".format(
                f_.get("critical", "?"), f_.get("high", "?"), f_.get("med", "?"),
                f_.get("low", "?"), f_.get("false_ticks", "?"))
            if "review_downgrade" in d:
                e["downgrade"] = True
        elif d["state"] in ("BUILT-GREEN", "BUILT-RED"):
            e["smoke"] = d.get("smoke_first_run", "?")
            e["cycles"] = d.get("cycles_to_green", "?")
        elif d["state"] == "VERIFIED":
            dp = d.get("defects_post_ship", {})
            e["defects"] = "{}/{}".format(dp.get("ed_side", "?"), dp.get("executor_side", "?"))
    return eds, len(lines)


def render(eds, nlines):
    rows = [
        "| ID | Tier | State | Last update | Vet C/H/M/L/FT | Smoke 1st | Cycles | Defects ED/exec |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for k in sorted(eds):
        e = eds[k]
        state = e["state"] + (" (downgraded review)" if e.get("downgrade") else "")
        rows.append("| {} | {} | {} | {} | {} | {} | {} | {} |".format(
            k, e.get("tier", "?"), state, e["ts"], e.get("vet", "-"),
            e.get("smoke", "-"), e.get("cycles", "-"), e.get("defects", "-")))
    latest = max(e["ts"] for e in eds.values())
    rows.append("")
    rows.append(
        f"{len(eds)} directives, {nlines} registry lines, latest change {latest}. "
        "Source of truth: `_directives/registry.jsonl`. "
        "Regenerate: `python3 execution-directives/derive-dashboard.py`.")
    return "\n".join(rows)


def splice(readme, block):
    with open(readme, encoding="utf-8") as f:
        text = f.read()
    b, e = text.count(BEGIN), text.count(END)
    if b != 1 or e != 1:
        die(f"expected exactly one marker pair in {readme}, got BEGIN={b} END={e}")
    if text.index(BEGIN) > text.index(END):
        die(f"marker order inverted in {readme} (END before BEGIN)")
    pre, rest = text.split(BEGIN, 1)
    _, post = rest.split(END, 1)
    new = pre + BEGIN + "\n" + block + "\n" + END + post
    if new == text:
        return False
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(os.path.abspath(readme)), prefix=".dash.")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(new)
        os.replace(tmp, readme)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise
    return True


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--registry", default=os.path.abspath(
        os.path.join(here, "..", "_directives", "registry.jsonl")))
    ap.add_argument("--readme", default=None,
                    help="dashboard host (default: dashboard.md next to the registry)")
    args = ap.parse_args()
    if args.readme is None:
        args.readme = os.path.join(os.path.dirname(os.path.abspath(args.registry)), "dashboard.md")
    if not os.path.isfile(args.readme):
        with open(args.readme, "w", encoding="utf-8") as f:
            f.write("# ED dashboard (derived — do not hand-edit)\n\n"
                    "<!-- ED-DASHBOARD:BEGIN generated by execution-directives/derive-dashboard.py; do not hand-edit -->\n"
                    "<!-- ED-DASHBOARD:END -->\n")
    eds, nlines = load(args.registry)
    changed = splice(args.readme, render(eds, nlines))
    print(f"dashboard {'updated' if changed else 'already current'}: "
          f"{len(eds)} directives from {nlines} lines -> {args.readme}")


if __name__ == "__main__":
    main()
