#!/usr/bin/env python3
"""Derive phase-latency + gridlock metrics from directives.jsonl (ED-062, idea.md item 6).

directives.jsonl is the ONLY status authority (USAGE.md); this script renders a derived
metrics view — stdout report + METRICS.md — so the framework's value gets measured instead
of asserted (USAGE.md: "the metrics fields ... are how the system's value gets measured").
Standalone and on-demand: NOT wired into append-registry.py or any hook.

Semantics (fixed, documented here because they are load-bearing):
  * First file-order occurrence per boundary wins — a re-append of the same boundary never
    moves it (REOPENED re-entries therefore do not rewrite history).
  * BUILT-GREEN and BUILT-RED collapse to one "BUILT" boundary for latency purposes.
  * A latency pair is counted only when BOTH boundary timestamps exist and the delta is
    >= 0; a negative delta (out-of-order ledger) is reported as an anomaly, not counted.
  * p90 = sorted values, nearest-rank method: value at index ceil(0.9 * n) - 1.
  * Current state = LAST LINE IN FILE ORDER, exactly like derive-dashboard.py — never
    max-by-timestamp (probed: ED-039 carries a backfilled GREENLIT stamped after its
    VERIFIED; ts-max would call it "stuck at GREENLIT" while the dashboard says VERIFIED).
  * "Gridlock" proxy = ids whose current state sits at a gate (DESIGN, VETTED, GREENLIT).
  * Gate-skip integrity: an id that reached BUILT/VERIFIED with no GREENLIT (or no VETTED)
    line EVER is reported (probed: ED-050 reached VERIFIED with no GREENLIT line — the
    framework's hardest rule, unrecorded).

Refuses (exit 2, nothing written) on malformed registry lines, mirroring
derive-dashboard.py's contract. Output file is written once, atomically (tmp +
os.replace). Deterministic: identical registry -> byte-identical METRICS.md.
"""
import argparse
import json
import math
import os
import sys
import tempfile
from datetime import datetime, timezone

STATES = {"DESIGN", "VETTED", "GREENLIT", "BUILT-GREEN", "BUILT-RED", "VERIFIED", "REOPENED"}
GATES = ("DESIGN", "VETTED", "GREENLIT")  # latest-state-here == waiting at a gate
PHASES = [  # (label, from-boundary, to-boundary)
    ("DESIGN -> VETTED", "DESIGN", "VETTED"),
    ("VETTED -> GREENLIT", "VETTED", "GREENLIT"),
    ("GREENLIT -> BUILT", "GREENLIT", "BUILT"),
    ("BUILT -> VERIFIED", "BUILT", "VERIFIED"),
    ("DESIGN -> VERIFIED", "DESIGN", "VERIFIED"),
]
HEADER = "<!-- generated by execution-directives/derive-metrics.py from directives.jsonl; do not hand-edit -->"


def die(msg):
    print(f"derive-metrics: {msg}", file=sys.stderr)
    sys.exit(2)


def parse_ts(raw, n):
    try:
        return datetime.fromisoformat(raw.replace("Z", "+00:00")).astimezone(timezone.utc)
    except ValueError:
        die(f"line {n}: unparseable ts {raw!r}")


def load(registry):
    """Validation contract mirrors derive-dashboard.py load() — refuse, never guess."""
    if not os.path.isfile(registry):
        die(f"registry not found: {registry}")
    with open(registry, encoding="utf-8") as f:
        lines = f.read().splitlines()
    if not lines:
        die("registry is empty")
    eds = {}
    for n, line in enumerate(lines, 1):
        if not line.strip():
            die(f"line {n}: blank line in append-only registry")
        try:
            d = json.loads(line)
        except json.JSONDecodeError as exc:
            die(f"line {n}: invalid JSON ({exc.msg})")
        missing = {"id", "state", "ts"} - d.keys()
        if missing:
            die(f"line {n}: missing required keys {sorted(missing)}")
        for key in ("id", "ts"):
            if not isinstance(d[key], str):
                die(f"line {n}: {key!r} must be a string, got {type(d[key]).__name__}")
        if d["state"] not in STATES:
            die(f"line {n}: unknown state {d['state']!r} (allowed: {sorted(STATES)})")
        ts = parse_ts(d["ts"], n)
        e = eds.setdefault(d["id"], {"bounds": {}, "latest": None, "latest_ts": None,
                                     "tier": "?", "wallclock": None, "false_ticks": None,
                                     "smoke_first": None, "cycles": None,
                                     "reopened": 0, "built_red": 0,
                                     "defects": None})
        state = d["state"]
        bound = "BUILT" if state in ("BUILT-GREEN", "BUILT-RED") else state
        e["bounds"].setdefault(bound, ts)  # first file-order occurrence per boundary wins
        # current state: LAST LINE IN FILE ORDER wins, matching derive-dashboard.py
        # (never max-by-ts — backfilled lines carry stale/late stamps, e.g. ED-039)
        e["latest"], e["latest_ts"] = state, ts
        if state == "DESIGN":
            e["tier"] = d.get("tier", "?")
        elif state == "VETTED":
            ft = d.get("findings", {}).get("false_ticks")
            if isinstance(ft, int) and e["false_ticks"] is None:
                e["false_ticks"] = ft
        elif state == "GREENLIT":
            w = d.get("authoring_wallclock_min")
            if isinstance(w, (int, float)) and e["wallclock"] is None:
                e["wallclock"] = float(w)
        elif state in ("BUILT-GREEN", "BUILT-RED"):
            if state == "BUILT-RED":
                e["built_red"] += 1
            if e["smoke_first"] is None:
                e["smoke_first"] = d.get("smoke_first_run", "?")
                c = d.get("cycles_to_green")
                e["cycles"] = c if isinstance(c, int) else None
            elif isinstance(d.get("cycles_to_green"), int):
                e["cycles"] = d["cycles_to_green"]  # later line knows the final cycle count
        elif state == "REOPENED":
            e["reopened"] += 1
        elif state == "VERIFIED":
            dp = d.get("defects_post_ship")
            if isinstance(dp, dict) and e["defects"] is None:
                e["defects"] = (dp.get("ed_side", 0), dp.get("executor_side", 0))
    return eds, len(lines)


def stats(values):
    """(n, median, p90, max) in minutes; None-safe for empty input."""
    if not values:
        return 0, None, None, None
    v = sorted(values)
    n = len(v)
    mid = n // 2
    median = v[mid] if n % 2 else (v[mid - 1] + v[mid]) / 2
    p90 = v[max(0, math.ceil(0.9 * n) - 1)]
    return n, median, p90, v[-1]


def fmt(m):
    return "-" if m is None else f"{m:.1f}m"


def compute(eds):
    lat = {label: [] for label, _, _ in PHASES}
    anomalies = []
    for k, e in eds.items():
        b = e["bounds"]
        for label, src, dst in PHASES:
            if src in b and dst in b:
                delta = (b[dst] - b[src]).total_seconds() / 60
                if delta < 0:
                    anomalies.append(f"{k}: {label} negative ({delta:.1f}m) — out-of-order ledger, excluded")
                else:
                    lat[label].append(delta)
    stuck = {g: sorted(k for k, e in eds.items() if e["latest"] == g) for g in GATES}
    gate_skips = []
    for k in sorted(eds):
        e = eds[k]
        b = e["bounds"]
        if "BUILT" in b or "VERIFIED" in b:
            missing = [g for g in ("VETTED", "GREENLIT") if g not in b]
            if missing:
                reached = "VERIFIED" if "VERIFIED" in b else "BUILT"
                # tier annotated: CEREMONY EDs historically appended DESIGN+VERIFIED only
                # (ED-049 §8 precedent), so a skip there is era-convention, not violation
                gate_skips.append(f"{k} ({e['tier']}): reached {reached} with no "
                                  f"{' or '.join(missing)} line ever")
    wallclocks = [e["wallclock"] for e in eds.values() if e["wallclock"] is not None]
    false_ticks = sum(e["false_ticks"] for e in eds.values() if e["false_ticks"] is not None)
    smoke_known = [e for e in eds.values() if e["smoke_first"] in ("GREEN", "RED")]
    smoke_green = sum(1 for e in smoke_known if e["smoke_first"] == "GREEN")
    multi_cycle = sorted(k for k, e in eds.items()
                         if isinstance(e["cycles"], int) and e["cycles"] > 1)
    built_red = sum(e["built_red"] for e in eds.values())
    reopened = sum(e["reopened"] for e in eds.values())
    defects = [e["defects"] for e in eds.values() if e["defects"] is not None]
    d_ed = sum(d[0] for d in defects if isinstance(d[0], int))
    d_ex = sum(d[1] for d in defects if isinstance(d[1], int))
    return {
        "lat": lat, "anomalies": anomalies, "stuck": stuck, "gate_skips": gate_skips,
        "wall": stats(wallclocks), "false_ticks": false_ticks,
        "smoke_green": smoke_green, "smoke_known": len(smoke_known),
        "multi_cycle": multi_cycle, "built_red": built_red, "reopened": reopened,
        "defects_ed": d_ed, "defects_exec": d_ex,
    }


def render(eds, nlines, m):
    latest = max(e["latest_ts"] for e in eds.values()).strftime("%Y-%m-%dT%H:%M:%SZ")
    out = [
        HEADER,
        "# ED Framework Metrics (derived)",
        "",
        f"{len(eds)} directives, {nlines} registry lines, latest ledger change {latest}.",
        "Source of truth: `dev/directives/directives.jsonl`. "
        "Regenerate: `python3 execution-directives/derive-metrics.py`.",
        "",
        "## Phase latency (first file-order occurrence per boundary; BUILT-GREEN/RED collapse to BUILT)",
        "",
        "| Phase | n | median | p90 | max |",
        "|---|---|---|---|---|",
    ]
    for label, _, _ in PHASES:
        n, med, p90, mx = stats(m["lat"][label])
        out.append(f"| {label} | {n} | {fmt(med)} | {fmt(p90)} | {fmt(mx)} |")
    out += ["", "## Gridlock (current state waiting at a gate; file-order last line wins)", ""]
    for g in GATES:
        ids = m["stuck"][g]
        out.append(f"- stuck at {g}: {len(ids)}" + (f" — {', '.join(ids)}" if ids else ""))
    out += ["", "## Gate-skip integrity (BUILT/VERIFIED with a lifecycle gate never recorded)", ""]
    if m["gate_skips"]:
        out += [f"- {s}" for s in m["gate_skips"]]
    else:
        out.append("- none")
    wn, wmed, wp90, wmax = m["wall"]
    out += [
        "",
        "## Quality counters",
        "",
        f"- authoring wallclock (GREENLIT lines): n={wn} median {fmt(wmed)} p90 {fmt(wp90)} max {fmt(wmax)}",
        f"- smoke first run: {m['smoke_green']}/{m['smoke_known']} GREEN",
        f"- cycles_to_green > 1: {len(m['multi_cycle'])}"
        + (f" — {', '.join(m['multi_cycle'])}" if m["multi_cycle"] else ""),
        f"- BUILT-RED lines: {m['built_red']}; REOPENED lines: {m['reopened']}",
        f"- cross-vet false ticks (total): {m['false_ticks']}",
        f"- defects post-ship: ED-side {m['defects_ed']}, executor-side {m['defects_exec']}",
    ]
    if m["anomalies"]:
        out += ["", "## Anomalies (excluded from latency)", ""]
        out += [f"- {a}" for a in m["anomalies"]]
    out.append("")
    return "\n".join(out)


def write_atomic(path, text):
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(os.path.abspath(path)), prefix=".metrics.")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--registry", default=os.path.abspath(
        os.path.join(here, "..", "..", "directives", "directives.jsonl")))
    ap.add_argument("--out", default=os.path.join(os.path.dirname(here), "METRICS.md"),
                    help="derived metrics file (default: dev/directive-framework/METRICS.md)")
    ap.add_argument("--no-write", action="store_true",
                    help="print the report to stdout only; touch nothing on disk")
    args = ap.parse_args()
    eds, nlines = load(args.registry)
    text = render(eds, nlines, compute(eds))
    print(text)
    if not args.no_write:
        write_atomic(args.out, text)
        print(f"derive-metrics: wrote {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
