#!/usr/bin/env python3
"""init-runtime.py — create/verify the per-project `_directives/` runtime substrate.

Shipped by ED-001 (Foundation). Idempotent: safe to run any number of times; a second
run changes nothing and reports "already initialized". This script is the seed of the
plugin's project-onboarding entry point.

Layout created under <project>/_directives/ (see RUNTIME-SPEC.md for the contract):
    PD/ DD/ VD/ ED/ RD/     packet directories, one per directive type
    registry.jsonl          append-only status registry (created zero-byte; first line
                            is appended by append-registry.py — validate-registry.py
                            reports "registry is empty" until then, by design)
    cursor.json             phase/role cursor (atomic writes only)
    checklist.md            per-project earned-items appendix; canonical walk list
                            stays in canon (execution-directives/CHECKLIST.md)
"""
import argparse
import datetime
import json
import os
import sys
import tempfile

SUBDIRS = ["PD", "DD", "VD", "ED", "RD"]
PHASES = ["planning", "design", "validation", "execution", "review"]
ROLES = ["orchestrator", "author", "coder", "reviewer", "idle"]

CHECKLIST_STUB = """\
# Per-project checklist appendix

The authoritative walk list lives in canon: execution-directives/CHECKLIST.md.
This file holds ONLY items earned by incidents in THIS project (same earned-tag
discipline). Walks run canon first, then this appendix.

## Earned items

*(none yet)*
"""


DASHBOARD_SKELETON = """\
# ED dashboard (derived — do not hand-edit)

<!-- ED-DASHBOARD:BEGIN generated by execution-directives/derive-dashboard.py; do not hand-edit -->
<!-- ED-DASHBOARD:END -->
"""


def create_exclusive(path, text):
    """O_EXCL first-create: never clobbers concurrent state (ED-003 hardening).
    Returns True if this call created the file, False if it already existed."""
    try:
        fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
    except FileExistsError:
        return False
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(text)
        f.flush()
        os.fsync(f.fileno())
    return True


def atomic_write(path, text):
    d = os.path.dirname(path) or "."
    fd, tmp = tempfile.mkstemp(dir=d, prefix=".tmp-init-")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
        tmp = None
    finally:
        if tmp is not None and os.path.exists(tmp):
            os.unlink(tmp)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--project", default=".",
                    help="project root to initialize (default: cwd)")
    ap.add_argument("--phase", default="planning", choices=PHASES,
                    help="initial cursor phase (default: planning)")
    ap.add_argument("--role", default="orchestrator", choices=ROLES,
                    help="initial cursor role (default: orchestrator)")
    args = ap.parse_args()

    project = os.path.abspath(args.project)
    if not os.path.isdir(project):
        print(f"init-runtime: project dir does not exist: {project}", file=sys.stderr)
        sys.exit(2)

    root = os.path.join(project, "_directives")
    created = []

    for sub in [""] + SUBDIRS:
        p = os.path.join(root, sub)
        if not os.path.isdir(p):
            os.makedirs(p, exist_ok=True)
            created.append(os.path.relpath(p, project))

    registry = os.path.join(root, "registry.jsonl")
    # zero-byte on purpose: append-registry.py requires the file to exist; the first
    # state line is appended through it, never written here. O_EXCL: a concurrent
    # init or append can never be truncated by this create.
    if create_exclusive(registry, ""):
        created.append(os.path.relpath(registry, project))

    cursor_path = os.path.join(root, "cursor.json")
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    cursor = {
        "phase": args.phase,
        "role": args.role,
        "active_directive": None,
        "boundary": None,
        "postpones_used": 0,
        "updated": now,
        "updated_by": "init-runtime",
    }
    if create_exclusive(cursor_path, json.dumps(cursor, indent=2) + "\n"):
        created.append(os.path.relpath(cursor_path, project))

    checklist = os.path.join(root, "checklist.md")
    if create_exclusive(checklist, CHECKLIST_STUB):
        created.append(os.path.relpath(checklist, project))

    dashboard = os.path.join(root, "dashboard.md")
    if create_exclusive(dashboard, DASHBOARD_SKELETON):
        created.append(os.path.relpath(dashboard, project))

    if created:
        print(f"init-runtime: initialized {root}")
        for c in created:
            print(f"  created {c}")
    else:
        print(f"init-runtime: already initialized (nothing to do): {root}")
    sys.exit(0)


if __name__ == "__main__":
    main()
